version: '3'
services:
  chat-gpt-test:
    restart: always
    build: .
    container_name: 'chat-gpt-test'
    working_dir: '/root/'
    tty: true
    env_file:
      - .env
    volumes:
      - ./opt:/root/opt